apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: jenkins
spec:
  storageClassName: jenkins-storage-class
  resources:
    requests:
      storage: 50Gi
  accessModes:
    - ReadWriteOnce
