apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus
  namespace: nexus
  labels:
    app: nexus
spec:
  storageClassName: nexus
  resources:
    requests:
      storage: 50Gi
  accessModes:
    - ReadWriteOnce
