apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: devops-tools
spec:
  storageClassName: jenkins-storage-class
  resources:
    requests:
      storage: 50Gi
  accessModes:
    - ReadWriteOnce
