apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jenkins-slave
    image: jaydeepuniverse/master-docker-image:1.0
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
    - mountPath: /var/maven/.m2 
      name: maven-repository
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
  - name: maven-repository
    hostPath:
      path: /home/ec2-user/efs/m2
