apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: petclinic
  namespace: petclinic
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: petclinic
      name: petclinic
    spec:
      containers:
        - image: >-
            jfrogArtifactoryURL:80/docker-local/spring-petclinic:${trigger["properties"]["BUILD_NUMBER"]}
          name: petclinic
      imagePullSecrets:
        - name: artifactoryCred
